app = "my-n8n-fly"


[env]
  GENERIC_TIMEZONE = "Europe/Athens"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
